{% set name = "affine" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 573514d5c37e98401a0ec34139c2b725d9f9ae4d074662f4b62a47d6a2ba9f06

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - python
    - pip
  run:
    - python
    - attrs

test:
  source_files:
    - affine/tests
  imports:
    - affine
  requires:
    - pip
    - pytest >=4.6
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name|lower }}')=='{{ version }}')"
    - pytest affine/tests -v

about:
  home: https://github.com/sgillies/affine
  license: BSD-3-Clause
  summary: Matrices describing affine transformation of the plane.
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    The Affine package is used to produce the affine transformation
    matrix.
  dev_url: https://github.com/sgillies/affine

extra:
  recipe-maintainers:
    - ocefpaf
