{% set version = "2.0.0.post1" %}

package:
    name: affine
    version: {{ version }}

source:
    fn: affine-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/a/affine/affine-{{ version }}.tar.gz
    md5: b7f4e2c86adc6575a7563c401d07f992

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    imports:
        - affine

about:
    home: https://github.com/sgillies/affine
    license: BSD 3-Clause
    summary: Matrices describing affine transformation of the plane

extra:
    recipe-maintainers:
        - ocefpaf
