travis:
  secure:
    BINSTAR_TOKEN: M4jYxU7KGTk3PpGKrNuzAceCLVrah+cXBYLs9N0PyNMEGbvqIxccV5MMKQvRxQCDA9nEF9mTqp0hy/uBh2xeMeUTfQEGiv1fUeuupbHmhiNm1l7TXpWlWUTn57Ap2FlyEnomqgHdBV+GtZU3ZchVmkD3UKgdKaB7/I4g9DiL68TCqYup+affYzwtfs3ICh66DGMmMbuvX4RCFzQHsZChs5LENvSc5+Mkg624nYJI1Zv9mSFQHTaccw71QMxrZLf24EQ1c75N+DU0/jf+U774jFYrt3WZL87gmZM68FwBxbOMhO1+ZNJ3sNbJhByTV0a29w5onT9OdHDqGlyFJBm8kWa4dchigTmCP8frN5NyYsaBMRuBqJOY4yCHSJtpwdB8DsPYtbzHF+qE7ThZtU8dy12GZbsWuVs32+Yn6KI5vvd9BqXJvkEXIJzS5mX7QZrUlBSqjJi51NhHLGTQMhpmaPnsns+47JugZz6AURZpwOjk6y4A4mIdqPFZiBNecvxNVfZDm+VGMp78YJOqb8/Xx4PWDYaXUgyMeq+sTqcDitdeQGRc5RA2WS8zvapkH+pKWrds//1zJE+ihsgktmUvTRv798QmhndjmAMFyN7ahUJ00VpnTJ7e/OLUc/YOtvsDAw9YdYLAz5TYeHIII4xVVCe2AapvDmN0BppV5grl5wo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
