travis:
  secure:
    BINSTAR_TOKEN: uGMD4/guiEQLIX0ehiPS2vlylvS8C1Ls0WfUwoq92pCebxFC2AeujPe5Fq2EfZsWN/+/+47jqa6qDCj510LYMyU7CBZo9I+ovtXf4io2IguTU/oLZYpKtVyAVPneNEogsc1h/3ezePdC2f4ZMurprkeqAbXQ8P2M4LM8X9Da91wLbUWE2J878hhKLt3XlNlhxL8pVKFovsJWexQRsR1fiQpTW4Skz06Q/+XTzhD+G+gvWfi3FqtTb8zlG7nH/CIG+DnRzYwlqQkD02k1nRPe3F9MZWnY3VEjB1k+ygle4xEZg5ivPn03YhDbbai2VdSoFuAhfyHFMIb6W37wMQIeifzDsQ0OW71FjOx6Voy+ZHwLpdyPAuAd9xK35hi6+Y+IwL3P4RyHRyK2910f6bK3nvckaGnYoaLCqpaqjIoDPiJ8LJG0XcwxHaAxo52mEz7vm6jhlkuh9LVpvtC8tRKyWK8IfKOYgeGoYOBwCnOW8CPwei5uL1OqAa1jyjWtYIwGmNf9XZUF4Prs3L29EHKnsoy7VBjlA8xpEScfi7u3emH0oSTpgMOGysfXoqZHj8xUgOcHJHVs56Zq6jyNhtegyzRyZuKZz7PPXO+yD37iKIluZbp8NuCYE/H+653jvWSmnPJAmDWvlcXBCVO7ds6/T49ZJyDwjXhqa7QDErVxCJY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
